var fs = require('fs');
fs.writeFileSync('notes.txt', 'asfdafdasfdHello my dear, this file has generated by Node JS application');


const appendData = ' /n appended content by through using append file method /n ';
/*fs.appendFile("notes.txt", appendData, (err) => {
    if (err) {
        console.log(err);
    } else {
        // Get the file contents after the append operation
        console.log("\nFile Contents of file after append:",
            fs.readFileSync("example_file.txt", "utf8"));
    }
});*/

fs.appendFile('notes.txt', appendData, (error) => {
    if (error) {
        console.log('error has been generated while appending content to notes.txt file')
    } else {
        console.log(`${appendData} : content has been appended properly`)
    }
})